### PR TITLE
Add section about pipeline file editors to tutorial misc

### PR DESCRIPTION
**Pull request by santus444**

### CODE REVIEW

**Comment by drnic** [comment]
Thanks for starting this. You'll also need to add the page into https://github.com/starkandwayne/concourse-tutorial/blob/master/mkdocs.yml so it appears in the Miscellaneous menu.

Try setting up `mkdocs` and run `mkdocs serve` to see that the page appears as you'd like.

**Comment by santus444** [comment]
Updated the mkdocs.yml. I have verified the MD doc in editor and GitHub previews. Yet to verify using mkdocs.

**Comment by santus444** [comment]
Page look good on `mkdocs` . 
screen shot 2018-02-23 at 8 21 48 am

**Comment by drnic** [comment]
Thanks!

**Pull request merged**
