### PR TITLE
Feature/random fixes

### PR DESCRIPTION
**Pull request by fauxstor**
Made the image links relative so they render online and in MacDown.

### CODE REVIEW

**Comment by drnic** [comment]
Have you confirmed that new image URLs still work when we publish the site?

Perhaps start with https://github.com/starkandwayne/concourse-tutorial#local-development-of-tutorial

**Comment by fauxstor** [comment]
Confirmed locally.

**Comment by norman-abramovitz** [comment]
@drnic What do you think if we only support mkdocs conventions instead of trying to support multiple markdown conventions.  People can use the mkdocs build command and then they can use their favorite HTTP server.  Trying to get the mkdocs markdown to work with Github or Mac Markdown without preprocessing just seems like an endless task.   This particular change would basically override a feature that mkdocs provides.

**Comment by drnic** [comment]
Yeah we should only accept things that work for the published website.

I’ve probably accidentally merged PRs that broke this by merging from my phone rather than checking that the PR builds correctly :(

**Comment by norman-abramovitz** [comment]
Per Dr Nic's comment,  I want to thank you for your PR but we will keep to the mkdocs convention as best as we can.  You should be able to do a `mkdocs build` and then you can use any HTTP server you want.  I know the output does work with nginx.

**Pull request closed without merging**
